package csc439team1.blackjack.model;

import java.util.ArrayList;

/**
 * Dealer class contains a private variable type Hand
 */
public class Dealer {
    /**
     * this is the collection of cards on the current Dealer hand
     */
    private Hand dealerHand = new Hand();

    /**
     * default no args constructor for Dealer()
     */
    public Dealer() {
    }


    /**
     * Getter method for Dealer's hand
     * @throws Exception will rethrow any exception generated by Hand or Card Classes.
     * @return dealer's hand.
     */
    public ArrayList<Card> getHand() {
        //Added try catch for any exceptions generated by Hand Class, and pass to Controller or CLIView. TS
        try
        {
            dealerHand.getCards();
        }
        catch (Exception e)
        {
            throw e;
        }
        return this.dealerHand.getCards();
    }

    /**
     * Adds a card to the dealer's hand.
     * @param card Card returned from shoe.pick() will be added to dealer's hand.
     * @throws Exception if generated by Hand or Card Classes.
     */
    public void addCard(Card card){
        //Added try/catch for any exceptions generated by Hand or Card Classes, and pass to Controller or CLIView. TS
        try {
            dealerHand.addCard(card);
        }
        catch (Exception e)
        {
            throw e;
        }
    }
}