package csc439team1.blackjack.model;

import java.util.ArrayList;
import java.util.logging.Logger;

/**
 * Shoe class contains the collections of deck objects
 * @author Trevor Sears
 * @author Will Sie
 * @author Conner Martin
 */
public class Shoe
{
    /**
     * Logger for Shoe class.
     */
    private static final Logger logger = Logger.getLogger(Card.class.getName());
    /**
     * an array list of deck called "shoe"
     */
    private ArrayList<Deck> shoe;

    /**
     * This is Shoe constructor that takes number of deck(s). Will throw IllegalArgumentException if a
     * number below 1 is entered.
     *
     * @param numberOfDecks the number of deck(s) taken from user input.
     * @throws IllegalArgumentException when user enters value of less than 1.
     */
    public Shoe(int numberOfDecks)  //Shoe constructor that takes number of deck(s)
    {
        logger.entering(getClass().getName(), "Shoe");
        if (numberOfDecks < 1){
            logger.warning("Exception thrown due to numberOfDecks being below 1, " + numberOfDecks);
            throw new IllegalArgumentException();
        }
        shoe = new ArrayList<>();   //initialize shoe as new array list

        //loop n times, n is the numberOfDecks that was taken from user input
        for (int totalDecks = 0; totalDecks < numberOfDecks; totalDecks++)
        {
            logger.info("Total decks " + totalDecks + ". Number of decks " + numberOfDecks + "of for loop");
            shoe.add(new Deck());   //add new deck to the shoe
        }
        logger.exiting(getClass().getName(), "Shoe");
    }

    /**
     * This is the method that will count the number of available deck(s) in the shoe
     *
     * @return the total number of deck(s) in the shoe
     */
    public int numDeck()
    {
        logger.entering(getClass().getName(), "numDeck");
        logger.severe("Issue related to the size of the Shoe: " + shoe.size());
        logger.exiting(getClass().getName(), "numDeck");
        //Call to size method from Arraylist returns the number of decks within the shoe.
        return shoe.size();
    }

    /**
     * This is the method that will pick one random card from the current shoe, and removes
     * empty decks from shoe. Method will also throw IllegalStateException should the shoe be
     * allowed to allowed to run below 1 deck.
     *
     * @return a random card by calling Deck.pick().
     * @throws IllegalStateException if shoe becomes empty.
     */
    public Card pick()
    {
        logger.entering(getClass().getName(), "pick");
        //Throws IllegalStatementException should game play neglect addressing an empty shoe.
        if (shoe.size() < 1)
        {
            logger.warning("Exception thrown to shoe size going below 1");
            throw new IllegalStateException();
        }
        /*Overall logic of pick method is creating an random int to access an deck within the shoe, create a card from
        what is returned by call to Deck class's pick method. Then checking if that was the last card for that deck,
        and removing the deck from shoe provided the condition is true. Using this method will remove the possibility
        pick method landing on an empty deck, as empty decks are removed within game play.*/

        //Creation of random int from 0 to number of decks within shoe.
        int randomDeck = (int) (Math.random() * numDeck());
        //Card generated by using pick method from Deck class.
        Card pickCard = (shoe.get(randomDeck)).pick();
        //if clause that will execute if no more cards are within the deck corresponding to randomDeck variable,
        //and remove that deck from the shoe.
        if ((shoe.get(randomDeck)).size() == 0)
        {
            logger.info("Deck " + randomDeck + "removed, due to no more cards within the deck");
            shoe.remove(randomDeck);
        }
        logger.info("randomDeck is " + randomDeck + ", card picked " + pickCard);
        logger.exiting(getClass().getName(), "pick");
        return pickCard;
    }

    /**
     * This is the method that will count the total card(s) in the shoe
     *
     * @return the total card(s) in the shoe
     */
    public int size()
    {
        logger.entering(getClass().getName(), "size");
        int totalCards = 0;
        for (Deck deck : shoe)
        {
            totalCards += deck.size();
            logger.config("totalCards value within for each: " + totalCards);
        }
        logger.info("End value of totalCards: " + totalCards);
        logger.exiting(getClass().getName(), "size");
        return totalCards; //return the total card(s) in the shoe
    }
}
